# Generated by Django 4.2.4 on 2023-08-04 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
